const standardDepartments = [
    "Computer Engineering", "Electrical and Electronics Engineering", "Mechanical Engineering", "Civil Engineering", "Industrial Engineering",
    "Architecture", "Medicine", "Dentistry", "Law", "Business Administration", "Economics", "International Relations", "Psychology", "Philosophy", "Sociology", "History",
    "French Language and Literature", "English Language and Literature", "Molecular Biology and Genetics", "Biology", "Chemistry", "Physics", "Mathematics",
    "Agricultural Engineering", "Theology", "Faculty of Education (Primary Teaching, Guidance etc.)", "Nursing", "Gastronomy and Culinary Arts",
    "Visual Communication Design", "Journalism"
];


const universityData = {
    German: {
      "Technische Universität München (TUM)": standardDepartments,
      "Ludwig-Maximilians-Universität München (LMU)": standardDepartments,
      "Ruprecht-Karls-Universität Heidelberg": standardDepartments,
      "Humboldt-Universität zu Berlin": standardDepartments,
      "Freie Universität Berlin": standardDepartments,
      "Technische Universität Berlin": standardDepartments,
      "Karlsruher Institut für Technologie (KIT)": standardDepartments,
      "RWTH Aachen University": standardDepartments,
      "Universität Freiburg": standardDepartments,
      "Universität Hamburg": standardDepartments,
      "Universität zu Köln (Cologne)": standardDepartments,
      "Universität Leipzig": standardDepartments,
      "Universität Stuttgart": standardDepartments,
      "Johann Wolfgang Goethe-Universität Frankfurt am Main": standardDepartments,
      "Universität Mannheim": standardDepartments,
      "Universität Bonn": standardDepartments,
      "Universität Düsseldorf (HHU)": standardDepartments,
      "Universität Erlangen-Nürnberg (FAU)": standardDepartments,
      "Universität Bremen": standardDepartments,
      "Universität Augsburg": standardDepartments,
      "Universität Duisburg-Essen": standardDepartments,
      "Universität Potsdam": standardDepartments,
      "Universität Ulm": standardDepartments,
      "Universität Regensburg": standardDepartments,
      "Universität Kiel (CAU)": standardDepartments,
      "Universität Jena (FSU)": standardDepartments,
      "Universität Magdeburg (OvGU)": standardDepartments,
      "Universität Rostock": standardDepartments,
      "Universität Hohenheim": standardDepartments,
      "Universität Wuppertal (BUW)": standardDepartments
    },
    Italy: {
      "Università di Bologna (UNIBO)": standardDepartments,
      "Sapienza Università di Roma": standardDepartments,
      "Università degli Studi di Padova": standardDepartments,
      "Università degli Studi di Milano (UniMi)": standardDepartments,
      "Politecnico di Milano": standardDepartments,
      "Politecnico di Torino": standardDepartments,
      "Università degli Studi di Torino": standardDepartments,
      "Università degli Studi di Napoli Federico II": standardDepartments,
      "Università degli Studi di Firenze (Floransa)": standardDepartments,
      "Università degli Studi di Pisa": standardDepartments,
      "Università degli Studi di Genova": standardDepartments,
      "Università degli Studi di Trento": standardDepartments,
      "Università degli Studi di Siena": standardDepartments,
      "Università degli Studi di Pavia": standardDepartments,
      "Università degli Studi di Palermo": standardDepartments,
      "Università degli Studi di Catania": standardDepartments,
      "Università degli Studi di Verona": standardDepartments,
      "Università degli Studi di Parma": standardDepartments,
      "Università degli Studi di Bari Aldo Moro": standardDepartments,
      "Università degli Studi dell'Aquila": standardDepartments,
      "Università degli Studi di Modena e Reggio Emilia": standardDepartments,
      "Università Ca' Foscari Venezia": standardDepartments,
      "Università degli Studi Roma Tre": standardDepartments,
      "Università degli Studi di Salerno": standardDepartments,
      "Università degli Studi di Perugia": standardDepartments,
      "Università degli Studi di Brescia": standardDepartments,
      "Università degli Studi di Udine": standardDepartments,
      "Università degli Studi di Messina": standardDepartments,
      "Università degli Studi di Lecce (Salento)": standardDepartments,
      "Università degli Studi di Trieste": standardDepartments
    },
    Spain: {
      "Universidad de Barcelona (UB)": standardDepartments,
      "Universidad Autónoma de Barcelona (UAB)": standardDepartments,
      "Universidad Complutense de Madrid (UCM)": standardDepartments,
      "Universidad Politécnica de Madrid (UPM)": standardDepartments,
      "Universidad de Valencia (UV)": standardDepartments,
      "Universidad de Sevilla": standardDepartments,
      "Universidad de Zaragoza (UNIZAR)": standardDepartments,
      "Universidad de Granada (UGR)": standardDepartments,
      "Universidad del País Vasco (UPV/EHU)": standardDepartments,
      "Universidad de Salamanca (USAL)": standardDepartments,
      "Universidad de Alcalá (UAH)": standardDepartments,
      "Universidad de Valladolid (UVA)": standardDepartments,
      "Universidad de Murcia (UMU)": standardDepartments,
      "Universidad de Santiago de Compostela (USC)": standardDepartments,
      "Universidad de Córdoba (UCO)": standardDepartments,
      "Universidad de Oviedo": standardDepartments,
      "Universidad de Cádiz (UCA)": standardDepartments,
      "Universidad de Málaga (UMA)": standardDepartments,
      "Universidad de La Laguna (ULL)": standardDepartments,
      "Universidad de Castilla-La Mancha (UCLM)": standardDepartments,
      "Universitat Politècnica de Catalunya (UPC)": standardDepartments,
      "Universitat Pompeu Fabra (UPF)": standardDepartments,
      "Universidad Rey Juan Carlos (URJC)": standardDepartments,
      "Universidad Pablo de Olavide (UPO)": standardDepartments,
      "Universidad de Navarra (UNAV)": standardDepartments,
      "Universitat de Lleida (UdL)": standardDepartments,
      "Universidad Miguel Hernández de Elche (UMH)": standardDepartments,
      "Universidad Rovira i Virgili (URV)": standardDepartments,
      "Universitat Jaume I (UJI)": standardDepartments,
      "Universitat de les Illes Balears (UIB)": standardDepartments
    },
    Turkey: {
        "Boğaziçi Üniversitesi": standardDepartments,
        "ODTÜ": standardDepartments,
        "İstanbul Teknik Üniversitesi": standardDepartments,
        "Hacettepe Üniversitesi": standardDepartments,
        "İstanbul Üniversitesi": standardDepartments,
        "Koç Üniversitesi": standardDepartments,
        "Sabancı Üniversitesi": standardDepartments,
        "Bilkent Üniversitesi": standardDepartments,
        "Ankara Üniversitesi": standardDepartments,
        "Ege Üniversitesi": standardDepartments,
        "İzmir Yüksek Teknoloji Enstitüsü": standardDepartments,
        "Marmara Üniversitesi": standardDepartments,
        "Yıldız Teknik Üniversitesi": standardDepartments,
        "Dokuz Eylül Üniversitesi": standardDepartments,
        "Çukurova Üniversitesi": standardDepartments,
        "Karadeniz Teknik Üniversitesi": standardDepartments,
        "Selçuk Üniversitesi": standardDepartments,
        "Atatürk Üniversitesi": standardDepartments,
        "Akdeniz Üniversitesi": standardDepartments,
        "İnönü Üniversitesi": standardDepartments,
        "Erciyes Üniversitesi": standardDepartments,
        "Eskişehir Osmangazi Üniversitesi": standardDepartments,
        "Anadolu Üniversitesi": standardDepartments,
        "Pamukkale Üniversitesi": standardDepartments,
        "Sakarya Üniversitesi": standardDepartments,
        "Kocaeli Üniversitesi": standardDepartments,
        "Gaziantep Üniversitesi": standardDepartments,
        "Dicle Üniversitesi": standardDepartments,
        "Fırat Üniversitesi": standardDepartments,
        "Mersin Üniversitesi": standardDepartments,
        "Hitit Üniversitesi": standardDepartments
      },
    Polond: {
      "University of Warsaw": standardDepartments,
      "Jagiellonian University (Kraków)": standardDepartments,
      "Warsaw University of Technology": standardDepartments,
      "AGH University of Science and Technology (Kraków)": standardDepartments,
      "Adam Mickiewicz University (Poznań)": standardDepartments,
      "Wrocław University of Science and Technology": standardDepartments,
      "Gdańsk University of Technology": standardDepartments,
      "Nicolaus Copernicus University (Toruń)": standardDepartments,
      "Łódź University of Technology": standardDepartments,
      "University of Wrocław": standardDepartments,
      "Poznań University of Technology": standardDepartments,
      "Silesian University of Technology (Gliwice)": standardDepartments,
      "University of Łódź": standardDepartments,
      "University of Gdańsk": standardDepartments,
      "Maria Curie-Skłodowska University (Lublin)": standardDepartments,
      "Cracow University of Technology": standardDepartments,
      "Kozminski University (Warsaw)": standardDepartments,
      "University of Economics in Katowice": standardDepartments,
      "SGH Warsaw School of Economics": standardDepartments,
      "University of Zielona Góra": standardDepartments,
      "Opole University of Technology": standardDepartments,
      "University of Rzeszów": standardDepartments,
      "Kazimierz Wielki University (Bydgoszcz)": standardDepartments,
      "University of Białystok": standardDepartments,
      "Jan Kochanowski University (Kielce)": standardDepartments,
      "University of Silesia in Katowice": standardDepartments,
      "University of Warmia and Mazury (Olsztyn)": standardDepartments,
      "Pomeranian Medical University (Szczecin)": standardDepartments,
      "Medical University of Warsaw": standardDepartments,
      "Medical University of Gdańsk": standardDepartments
    },
    Romania: {
      "University of Bucharest": standardDepartments,
      "Babeș-Bolyai University (Cluj-Napoca)": standardDepartments,
      "Alexandru Ioan Cuza University (Iași)": standardDepartments,
      "Politehnica University of Bucharest": standardDepartments,
      "Gheorghe Asachi Technical University of Iași": standardDepartments,
      "West University of Timișoara": standardDepartments,
      "Transilvania University of Brașov": standardDepartments,
      "Technical University of Cluj-Napoca": standardDepartments,
      "University of Craiova": standardDepartments,
      "Lucian Blaga University of Sibiu": standardDepartments,
      "Ovidius University of Constanța": standardDepartments,
      "Ștefan cel Mare University of Suceava": standardDepartments,
      "Valahia University of Târgoviște": standardDepartments,
      "Vasile Alecsandri University of Bacău": standardDepartments,
      "Petroleum-Gas University of Ploiești": standardDepartments,
      "University of Oradea": standardDepartments,
      "University of Pitești": standardDepartments,
      "University of Galați (Dunărea de Jos)": standardDepartments,
      "Constantin Brâncuși University of Târgu Jiu": standardDepartments,
      "1 Decembrie 1918 University of Alba Iulia": standardDepartments,
      "University of Medicine and Pharmacy Carol Davila (Bucharest)": standardDepartments,
      "Iuliu Hațieganu University of Medicine and Pharmacy (Cluj-Napoca)": standardDepartments,
      "Titu Maiorescu University": standardDepartments,
      "Spiru Haret University": standardDepartments,
      "Romanian-American University": standardDepartments,
      "National University of Arts Bucharest": standardDepartments,
      "Bucharest University of Economic Studies (ASE)": standardDepartments
    },
    Holland: {
      "Delft University of Technology (TU Delft)": standardDepartments,
      "University of Amsterdam (UvA)": standardDepartments,
      "Eindhoven University of Technology (TU/e)": standardDepartments,
      "Leiden University": standardDepartments,
      "Utrecht University": standardDepartments,
      "Erasmus University Rotterdam": standardDepartments,
      "Vrije Universiteit Amsterdam (VU)": standardDepartments,
      "University of Groningen (RUG)": standardDepartments,
      "Radboud University": standardDepartments,
      "Maastricht University": standardDepartments,
      "Wageningen University & Research": standardDepartments,
      "Tilburg University": standardDepartments,
      "University of Twente": standardDepartments,
      "Open University of the Netherlands": standardDepartments,
      "HAN University of Applied Sciences": standardDepartments,
      "Avans University of Applied Sciences": standardDepartments,
      "Fontys University of Applied Sciences": standardDepartments,
      "HZ University of Applied Sciences": standardDepartments,
      "Inholland University of Applied Sciences": standardDepartments,
      "NHL Stenden University of Applied Sciences": standardDepartments,
      "Saxion University of Applied Sciences": standardDepartments,
      "The Hague University of Applied Sciences": standardDepartments,
      "Amsterdam University of Applied Sciences": standardDepartments,
      "Rotterdam University of Applied Sciences": standardDepartments,
      "Zuyd University of Applied Sciences": standardDepartments,
      "Windesheim University of Applied Sciences": standardDepartments,
      "ArtEZ University of the Arts": standardDepartments,
      "Gerrit Rietveld Academie": standardDepartments,
      "Design Academy Eindhoven": standardDepartments
    },
    Belgium: {
      "KU Leuven (Katholieke Universiteit Leuven)": standardDepartments,
      "Université catholique de Louvain (UCLouvain)": standardDepartments,
      "Ghent University (Universiteit Gent)": standardDepartments,
      "Université libre de Bruxelles (ULB)": standardDepartments,
      "Vrije Universiteit Brussel (VUB)": standardDepartments,
      "University of Antwerp (Universiteit Antwerpen)": standardDepartments,
      "Université de Liège (ULiège)": standardDepartments,
      "Hasselt University (UHasselt)": standardDepartments,
      "Université de Namur (UNamur)": standardDepartments,
      "Université Saint-Louis - Bruxelles": standardDepartments,
      "Artesis Plantijn University College": standardDepartments,
      "Thomas More University of Applied Sciences": standardDepartments,
      "Howest University of Applied Sciences": standardDepartments,
      "Karel de Grote University of Applied Sciences and Arts": standardDepartments,
      "PXL University of Applied Sciences and Arts": standardDepartments,
      "University College Ghent (HoGent)": standardDepartments,
      "Haute École Léonard de Vinci": standardDepartments,
      "Haute École Provinciale de Hainaut - Condorcet": standardDepartments,
      "Haute École Francisco Ferrer": standardDepartments,
      "Haute École en Hainaut (HEH)": standardDepartments,
      "Haute École Lucia de Brouckère": standardDepartments,
      "Haute École de la Province de Liège": standardDepartments,
      "Odisee University College": standardDepartments,
      "Erasmushogeschool Brussel": standardDepartments,
      "LUCA School of Arts": standardDepartments,
      "Artevelde University of Applied Sciences": standardDepartments,
      "UC Leuven-Limburg (UCLL)": standardDepartments,
      "HELMo - Haute École Libre Mosane": standardDepartments,
      "Haute École Albert Jacquard": standardDepartments,
      "Haute École de la Ville de Liège": standardDepartments
    },
    Portugal: {
      "University of Lisbon (ULisboa)": standardDepartments,
      "University of Porto (U.Porto)": standardDepartments,
      "University of Coimbra (UC)": standardDepartments,
      "NOVA University Lisbon": standardDepartments,
      "University of Minho (UMinho)": standardDepartments,
      "University of Aveiro": standardDepartments,
      "University of Évora": standardDepartments,
      "University of Algarve": standardDepartments,
      "University of Beira Interior (UBI)": standardDepartments,
      "ISCTE - University Institute of Lisbon": standardDepartments,
      "Católica Lisbon School of Business & Economics": standardDepartments,
      "Polytechnic Institute of Lisbon": standardDepartments,
      "Polytechnic Institute of Porto (IPP)": standardDepartments,
      "Polytechnic Institute of Coimbra": standardDepartments,
      "Polytechnic Institute of Leiria": standardDepartments,
      "Polytechnic Institute of Setúbal": standardDepartments,
      "Polytechnic Institute of Cávado and Ave": standardDepartments,
      "Polytechnic Institute of Bragança": standardDepartments,
      "Polytechnic Institute of Viseu": standardDepartments,
      "University Fernando Pessoa": standardDepartments,
      "Portucalense University (UPT)": standardDepartments,
      "Lusíada University": standardDepartments,
      "Autónoma University of Lisbon": standardDepartments,
      "University Lusófona": standardDepartments,
      "Instituto Superior Técnico (IST)": standardDepartments,
      "Instituto Politécnico da Guarda": standardDepartments
    },
    Greece: {
      "National and Kapodistrian University of Athens (EKPA)": standardDepartments,
      "Aristotle University of Thessaloniki": standardDepartments,
      "University of Patras": standardDepartments,
      "University of Crete": standardDepartments,
      "University of Thessaly": standardDepartments,
      "Athens University of Economics and Business (AUEB)": standardDepartments,
      "University of Ioannina": standardDepartments,
      "Technical University of Crete": standardDepartments,
      "Democritus University of Thrace": standardDepartments,
      "University of the Aegean": standardDepartments,
      "Harokopio University of Athens": standardDepartments,
      "Panteion University of Social and Political Sciences": standardDepartments,
      "University of West Attica": standardDepartments,
      "International Hellenic University": standardDepartments,
      "Hellenic Open University": standardDepartments,
      "University of Macedonia": standardDepartments,
      "Agricultural University of Athens": standardDepartments,
      "School of Pedagogical and Technological Education (ASPETE)": standardDepartments,
      "Ionian University": standardDepartments,
      "University of Western Macedonia": standardDepartments,
      "University of Peloponnese": standardDepartments,
      "University of Central Greece (UCG)": standardDepartments,
      "Technological Educational Institute of Epirus": standardDepartments,
      "Technological Educational Institute of Thessaly": standardDepartments
    },
  };

  export default universityData;
